base_config: "../SimPyABM/config.yaml"
outdir: "../results"
experiment: "avg_employee_5"
repetitions: 30
base_seed: 0
workers: 8

simulation:
  num_vehicles_per_day_min: [120]
  num_vehicles_per_day_max: [120]

charging_column:
  fast_charging_column:
    quantity: [30]
  slow_charging_column:
    quantity: [0]
  strategy: ["FCFS", "SHRD"]

grid:
  energy_grid:
    max_power_kW: [100000]